<?php echo (isset($this->alert) ? $this->alert : '');?>
<form method="post" action="<?php echo BASE;?>cadastro/cadastrar/">
   <div class="form-group row">
      <label for="name" class="col-sm-2 col-form-label">Nome Completo</label>
      <div class="col-sm-10">
        <input type="text" name="name" class="form-control" id="name" placeholder="Nome" required value="<?php echo $this->request->post('name') ?>">
      </div>
    </div>
    <div class="form-group row">
      <label for="email" class="col-sm-2 col-form-label">Email</label>
      <div class="col-sm-10">
        <input type="email" name="email" class="form-control" id="email" placeholder="Email" required value="<?php echo $this->request->post('email') ?>">
      </div>
    </div>
    <div class="form-group row">
      <label for="username" class="col-sm-2 col-form-label">Username</label>
      <div class="col-sm-10">
        <input type="text" name="username" class="form-control" id="username" placeholder="Username" required value="<?php echo $this->request->post('username') ?>">
      </div>
    </div>
    <div class="form-group row">
      <label for="password" class="col-sm-2 col-form-label">Senha</label>
      <div class="col-sm-10">
        <input type="password" name="password" class="form-control" id="password" placeholder="Senha" required>
      </div>
    </div>
 
    <div class="form-group row">
      <div class="offset-sm-2 col-sm-10">
        <button type="submit" class="btn btn-primary">Sign in</button>
      </div>
    </div>
  </form>