<form>
    <div class="alert alert-bloc alert-info"><h4>RECUPERE SUA SENHA</h4></div>
    <div class="form-group row">
      <label for="username" class="col-sm-2 col-form-label">Username</label>
      <div class="col-sm-10">
        <input type="text" class="form-control" id="username" placeholder="Username">
      </div>
    </div>
 
    <div class="form-group row">
      <div class="offset-sm-2 col-sm-10">
        <button type="submit" class="btn btn-primary">Enviar Link</button>
      </div>
    </div>
  </form>